"use client";
import {useEffect,useMemo,useState} from "react";
import {products as fallbackProducts} from "../lib/products";
import {supabase} from "../lib/supabase";
type CatalogProduct=(typeof fallbackProducts)[number];
export default function Home(){const[catalog,setCatalog]=useState<CatalogProduct[]>(fallbackProducts),[filter,setFilter]=useState("All"),[cart,setCart]=useState<string[]>([]),[cartOpen,setCartOpen]=useState(false),[faq,setFaq]=useState(0);useEffect(()=>{void(async()=>{const{data}=await supabase.from("products").select("slug,name,category,short_description,regular_price_cents,sale_price_cents,sale_starts_at,sale_ends_at,is_active,is_purchasable,sort_order").eq("is_active",true).eq("is_purchasable",true).order("sort_order");if(!data)return;const now=Date.now();const synced=data.map(row=>{const base=fallbackProducts.find(p=>p.slug===row.slug);if(!base)return null;const inWindow=(!row.sale_starts_at||Date.parse(row.sale_starts_at)<=now)&&(!row.sale_ends_at||Date.parse(row.sale_ends_at)>=now);const sale=inWindow&&row.sale_price_cents!==null;return{...base,name:row.name,type:row.category,desc:row.short_description,regularPrice:row.regular_price_cents/100,price:(sale?row.sale_price_cents:row.regular_price_cents)/100,tag:sale?`LAUNCH $${row.sale_price_cents/100}`:""};}).filter((p):p is CatalogProduct=>p!==null);setCatalog(synced);})()},[]);const shown=useMemo(()=>filter==="All"?catalog:catalog.filter(p=>p.type===filter),[filter,catalog]);const total=cart.reduce((s,slug)=>s+(catalog.find(p=>p.slug===slug)?.price||0),0);const add=(slug:string)=>{setCart(c=>[...c,slug]);setCartOpen(true)};return <main>
<nav><a className="brand" href="#top">AZRI<span>—</span>L <small>LABS</small></a><div className="links"><a href="/story">Story</a><a href="#plugins">Plugins</a><a href="#vision">Philosophy</a></div><button onClick={()=>setCartOpen(true)}>CART <b>{String(cart.length).padStart(2,"0")}</b></button></nav>
<section className="hero" id="top"><div className="grid"/><div className="glow"/><div className="copy"><p className="eyebrow">● &nbsp; ART × SCIENCE × TECHNOLOGY</p><h1>WHERE <em>ART</em><br/>MEETS SCIENCE<br/>THROUGH SOUND.</h1><p className="intro">Azri-L Labs creates audio instruments at the intersection of artistic instinct, scientific understanding and technological invention.</p><div className="actions"><a className="primary" href="#plugins">EXPLORE THE TOOLS <span>↘</span></a><a href="/story">Read the personal story →</a></div></div><div className="wave">{[10,18,8,32,54,24,70,42,92,56,78,38,60,26].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></section>
<section className="story" id="story"><p className="index">01 / PHILOSOPHY</p><div><p className="kicker">THREE DISCIPLINES. ONE LANGUAGE.</p><h2>Art gives us the question.<br/><em>Science reveals</em> the pattern.<br/>Technology makes it tangible.</h2><p className="body">We do not see creativity and precision as opposites. Every Azri-L instrument begins with a musical feeling, is examined through acoustics and perception, and becomes a focused technology that supports — rather than interrupts — the creative process.</p><div className="pillars">{[["01","ART","Emotion, taste and the courage to make something that did not exist."],["02","SCIENCE","Acoustics, psychoacoustics and measurable relationships inside sound."],["03","TECHNOLOGY","Precise systems that turn complex knowledge into intuitive action."]].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><p>{x[2]}</p></article>)}</div></div></section>
<section className="vision" id="vision"><p>FEELING ───────── KNOWLEDGE ───────── POSSIBILITY</p><h2>Creative instinct,<br/>made visible through <em>technology.</em></h2></section>
<section className="shop" id="plugins"><header><div><p className="kicker">THE i SEE FAMILY</p><h2>Choose one focus.<br/>Or see it all.</h2></div><p>Buy each component as a focused plugin, use every capability together inside i See All, or own both formats with the Complete Bundle.</p></header><div className="filters">{["All","Analyzer","Meters","Timeline","Waveform","All-in-one","Bundle"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}<span>{shown.length} PRODUCTS</span></div><div className="products">{shown.map(p=><article className="product" key={p.slug}><a href={`/products/${p.slug}`} className="visual" style={{"--accent":p.color} as React.CSSProperties}>{p.tag&&<small>{p.tag}</small>}<div className="box"><span>AZRI—L</span><strong>{p.name}</strong><i/></div></a><div className="info"><span>{p.type.toUpperCase()} / VST3 · AU</span><h3><a href={`/products/${p.slug}`}>{p.name}</a></h3><p>{p.desc}</p><div><b className="saleprice"><s>${p.regularPrice}</s> ${p.price}</b><button onClick={()=>add(p.slug)}>ADD TO CART <i>+</i></button></div><a className="details" href={`/products/${p.slug}`}>VIEW PRODUCT DETAILS →</a></div></article>)}</div></section>
<section className="manifest"><p className="kicker">DESIGNED BETWEEN DISCIPLINES.</p><h2>Every measurement<br/>serves a feeling.</h2><p>Made for creators who want scientific precision without losing artistic instinct.</p></section>
<section className="faq"><p className="index">SUPPORT / FAQ</p><div>{[["Which formats are supported?","VST3 and Audio Unit for current macOS and Windows systems."],["How many computers can I activate?","A personal license covers up to three machines that you own."],["Do I get future updates?","Yes. All minor updates are included."]].map((x,i)=><article key={i}><button onClick={()=>setFaq(faq===i?-1:i)}>{x[0]} <b>{faq===i?"−":"+"}</b></button>{faq===i&&<p>{x[1]}</p>}</article>)}</div></section>
<footer><div className="brand">AZRI<span>—</span>L <small>LABS</small></div><p>Art. Science. Technology. Sound.</p><small>© 2026 AZRI-L LABS</small></footer>
{cartOpen&&<><button className="backdrop" aria-label="Close cart" onClick={()=>setCartOpen(false)}/><aside role="dialog" aria-label="Shopping cart"><button className="close" onClick={()=>setCartOpen(false)}>×</button><p className="kicker">YOUR CART</p><h2>{cart.length?`${cart.length} tool${cart.length>1?"s":""} selected`:"Your cart is empty"}</h2>{cart.map((slug,i)=>{const p=catalog.find(x=>x.slug===slug)!;return <div className="cartrow" key={`${slug}-${i}`}><span>{p.name}</span><b>${p.price}</b><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>Remove</button></div>})}{cart.length>0&&<><div className="total"><span>TOTAL</span><b>${total}</b></div><button className="checkout">SECURE CHECKOUT →</button></>}</aside></>}</main>}
