"use client";
import {useMemo,useState} from "react";
const products=[{id:1,name:"PRISM",type:"Analyzer",price:49,tag:"BESTSELLER",color:"#8b5cf6",desc:"See your mix the way a DJ system reads it."},{id:2,name:"LOW//CUT",type:"Filter",price:29,tag:"NEW",color:"#21d4c2",desc:"Transparent low-end control. Surgical by design."},{id:3,name:"PULSE GRID",type:"Utility",price:39,tag:"",color:"#f36bd5",desc:"Phase, timing and groove — locked into one view."}];
export default function Home(){const[filter,setFilter]=useState("All"),[cart,setCart]=useState<number[]>([]),[cartOpen,setCartOpen]=useState(false),[faq,setFaq]=useState(0);const shown=useMemo(()=>filter==="All"?products:products.filter(p=>p.type===filter),[filter]);const total=cart.reduce((s,id)=>s+(products.find(p=>p.id===id)?.price||0),0);const add=(id:number)=>{setCart(c=>[...c,id]);setCartOpen(true)};return <main>
<nav><a className="brand" href="#top">AZRI<span>—</span>L <small>LABS</small></a><div className="links"><a href="#story">Story</a><a href="#plugins">Plugins</a><a href="#vision">Vision</a></div><button onClick={()=>setCartOpen(true)}>CART <b>{String(cart.length).padStart(2,"0")}</b></button></nav>
<section className="hero" id="top"><div className="grid"/><div className="glow"/><div className="copy"><p className="eyebrow">● &nbsp; INDEPENDENT AUDIO TECHNOLOGY</p><h1>BUILDING TOOLS<br/>FOR <em>THE SOUND</em><br/>THAT COMES NEXT.</h1><p className="intro">Azri-L Labs is where electronic music, precision engineering and restless curiosity become instruments for modern creators.</p><div className="actions"><a className="primary" href="#plugins">EXPLORE PLUGINS <span>↘</span></a><a href="#story">Discover the story ↓</a></div></div><div className="wave">{[10,18,8,32,54,24,70,42,92,56,78,38,60,26].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></section>
<section className="story" id="story"><p className="index">01 / ORIGIN</p><div><p className="kicker">ARTIST × BUILDER</p><h2>Born in the gap between<br/><em>what I heard</em> and what<br/>the tools could show me.</h2><p className="body">Azri-L began as an artist project — late nights, club systems and an obsession with the smallest details of sound. The software grew from the same instinct: if the right tool doesn’t exist, build it.</p><div className="pillars">{[["01","MUSIC","Tech House · Afro House · Indie Dance"],["02","CODE","Native DSP · JUCE · VST3"],["03","PURPOSE","Less friction. Better decisions. More feeling."]].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><p>{x[2]}</p></article>)}</div></div></section>
<section className="vision" id="vision"><p>FROM CLUB INSTINCT ───────────────── TO STUDIO PRECISION</p><h2>Sound is emotional.<br/>The tools should be <em>exact.</em></h2></section>
<section className="shop" id="plugins"><header><div><p className="kicker">AZRI-L SOFTWARE</p><h2>Tools built for<br/>real-world sessions.</h2></div><p>Focused audio software with a clear job, a fast workflow and no unnecessary complexity. One license. Your machines. Free updates.</p></header><div className="filters">{["All","Analyzer","Filter","Utility"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}<span>{shown.length} PRODUCTS</span></div><div className="products">{shown.map(p=><article className="product" key={p.id}><div className="visual" style={{"--accent":p.color} as React.CSSProperties}>{p.tag&&<small>{p.tag}</small>}<div className="box"><span>AZRI—L</span><strong>{p.name}</strong><i/></div></div><div className="info"><span>{p.type.toUpperCase()} / VST3 · AU</span><h3>{p.name}</h3><p>{p.desc}</p><div><b>${p.price}</b><button onClick={()=>add(p.id)}>ADD TO CART <i>+</i></button></div></div></article>)}</div></section>
<section className="manifest"><p className="kicker">NO BLOAT. NO GIMMICKS.</p><h2>Every control earns<br/>its place.</h2><p>Made for producers who care how things feel — and need to trust what they see.</p></section>
<section className="faq"><p className="index">SUPPORT / FAQ</p><div>{[["Which formats are supported?","VST3 and Audio Unit for current macOS and Windows systems."],["How many computers can I activate?","A personal license covers up to three machines that you own."],["Do I get future updates?","Yes. All minor updates are included."]].map((x,i)=><article key={i}><button onClick={()=>setFaq(faq===i?-1:i)}>{x[0]} <b>{faq===i?"−":"+"}</b></button>{faq===i&&<p>{x[1]}</p>}</article>)}</div></section>
<footer><div className="brand">AZRI<span>—</span>L <small>LABS</small></div><p>Tools for the sound that comes next.</p><small>© 2026 AZRI-L LABS</small></footer>
{cartOpen&&<><button className="backdrop" aria-label="Close cart" onClick={()=>setCartOpen(false)}/><aside role="dialog" aria-label="Shopping cart"><button className="close" onClick={()=>setCartOpen(false)}>×</button><p className="kicker">YOUR CART</p><h2>{cart.length?`${cart.length} tool${cart.length>1?"s":""} selected`:"Your cart is empty"}</h2>{cart.map((id,i)=>{const p=products.find(x=>x.id===id)!;return <div className="cartrow" key={`${id}-${i}`}><span>{p.name}</span><b>${p.price}</b><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>Remove</button></div>})}{cart.length>0&&<><div className="total"><span>TOTAL</span><b>${total}</b></div><button className="checkout">SECURE CHECKOUT →</button></>}</aside></>}</main>}
